### PR TITLE
Add processing_level_id collection parameter

### LINKED ISSUE #76: Support searching for collection by processing_level
See https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html#c-processing-level-id

### PR DESCRIPTION
**Pull request by WardBrian**
Closes #76

### CODE REVIEW

**Review by chuckwondo — CHANGES_REQUESTED** [review]
Thank you for your contribution! Please add an entry to CHANGELOG.md.

**Review by chuckwondo — APPROVED** [review]
Perfect. Thank you!

**Comment by WardBrian** [comment]
Thanks @chuckwondo - do you have a sense of when the next release to PyPI would be?

**Comment by chuckwondo** [comment]
> Thanks @chuckwondo - do you have a sense of when the next release to PyPI would be?

Good question. @frankinspace, any thoughts on this?

**Comment by frankinspace** [comment]
@chuckwondo let's discuss: https://github.com/nasa/python_cmr/issues/84

**Pull request merged**
